services:
  - type: web
    name: bsng-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
